import { MD3LightTheme, MD3DarkTheme } from "react-native-paper";

export const appThemes = {
  light: {
    // TEMPLAR GOLD (Convento)
    convento: {
      ...MD3LightTheme,
      roundness: 8,
      colors: {
        ...MD3LightTheme.colors,
        primary: "#914c00",
        onPrimary: "#ffffff",
        primaryContainer: "#ff8a00",
        onPrimaryContainer: "#613100",
        inversePrimary: "#ffb77f",
        primaryFixed: "#ffdcc4",
        primaryFixedDim: "#ffb77f",
        onPrimaryFixed: "#2f1500",
        onPrimaryFixedVariant: "#6f3900",

        secondary: "#715a42",
        onSecondary: "#ffffff",
        secondaryContainer: "#fadabc",
        onSecondaryContainer: "#765e46",
        secondaryFixed: "#fdddbf",
        secondaryFixedDim: "#e0c1a4",
        onSecondaryFixed: "#281806",
        onSecondaryFixedVariant: "#58432d",

        tertiary: "#695c4e",
        onTertiary: "#ffffff",
        tertiaryContainer: "#b6a695",
        onTertiaryContainer: "#463c2f",
        tertiaryFixed: "#f1e0cd",
        tertiaryFixedDim: "#d4c4b2",
        onTertiaryFixed: "#231a0f",
        onTertiaryFixedVariant: "#504538",

        error: "#ba1a1a",
        onError: "#ffffff",
        errorContainer: "#ffdad6",
        onErrorContainer: "#93000a",

        background: "#fff8f5",
        onBackground: "#241912",
        surface: "#fff8f5",
        onSurface: "#241912",
        surfaceVariant: "#f3dfd1",
        onSurfaceVariant: "#564334",
        surfaceDim: "#ebd6c9",
        surfaceBright: "#fff8f5",
        surfaceContainerLowest: "#ffffff",
        surfaceContainerLow: "#fff1e9",
        surfaceContainer: "#ffeadd",
        surfaceContainerHigh: "#f9e4d7",
        surfaceContainerHighest: "#f3dfd1",
        surfaceTint: "#914c00",
        inverseSurface: "#3a2e25",
        inverseOnSurface: "#ffede3",
        outline: "#8a7362",
        outlineVariant: "#ddc1ae",
      },
    },

    // MUTED MOSS (Mata - Atualizado)
    mata: {
      ...MD3LightTheme,
      roundness: 8, // Atualizado para 0.5rem (8px) base
      colors: {
        ...MD3LightTheme.colors,
        primary: "#476500",
        onPrimary: "#ffffff",
        primaryContainer: "#5d7f13",
        onPrimaryContainer: "#faffe7",
        inversePrimary: "#add461",
        primaryFixed: "#c8f17a",
        primaryFixedDim: "#add461",
        onPrimaryFixed: "#131f00",
        onPrimaryFixedVariant: "#364e00",

        secondary: "#546348",
        onSecondary: "#ffffff",
        secondaryContainer: "#d5e5c3",
        onSecondaryContainer: "#58674c",
        secondaryFixed: "#d7e8c6",
        secondaryFixedDim: "#bcccab",
        onSecondaryFixed: "#131f09",
        onSecondaryFixedVariant: "#3d4b32",

        tertiary: "#5a5d58",
        onTertiary: "#ffffff",
        tertiaryContainer: "#727570",
        onTertiaryContainer: "#fbfdf6",
        tertiaryFixed: "#e1e3dc",
        tertiaryFixedDim: "#c5c7c1",
        onTertiaryFixed: "#191c18",
        onTertiaryFixedVariant: "#444843",

        error: "#ba1a1a",
        onError: "#ffffff",
        errorContainer: "#ffdad6",
        onErrorContainer: "#93000a",

        background: "#f9faf7",
        onBackground: "#191c1b",
        surface: "#f9faf7",
        onSurface: "#191c1b",
        surfaceVariant: "#e2e3e0",
        onSurfaceVariant: "#444939",
        surfaceDim: "#d9dad8",
        surfaceBright: "#f9faf7",
        surfaceContainerLowest: "#ffffff",
        surfaceContainerLow: "#f3f4f1",
        surfaceContainer: "#edeeeb",
        surfaceContainerHigh: "#e7e8e6",
        surfaceContainerHighest: "#e2e3e0",
        surfaceTint: "#496800",
        inverseSurface: "#2e312f",
        inverseOnSurface: "#f0f1ee",
        outline: "#747967",
        outlineVariant: "#c4c9b4",
      },
    },

    // TEMPLAR RED (Tabuleiros)
    tabuleiros: {
      ...MD3LightTheme,
      roundness: 8,
      colors: {
        ...MD3LightTheme.colors,
        primary: "#8f000d",
        onPrimary: "#ffffff",
        primaryContainer: "#b22222",
        onPrimaryContainer: "#ffc8c2",
        inversePrimary: "#ffb4ac",
        primaryFixed: "#ffdad6",
        primaryFixedDim: "#ffb4ac",
        onPrimaryFixed: "#410003",
        onPrimaryFixedVariant: "#92030f",

        secondary: "#5f5e5e",
        onSecondary: "#ffffff",
        secondaryContainer: "#e4e2e1",
        onSecondaryContainer: "#656464",
        secondaryFixed: "#e4e2e1",
        secondaryFixedDim: "#c8c6c5",
        onSecondaryFixed: "#1b1c1c",
        onSecondaryFixedVariant: "#474747",

        tertiary: "#4a4538",
        onTertiary: "#ffffff",
        tertiaryContainer: "#625c4f",
        onTertiaryContainer: "#ded5c4",
        tertiaryFixed: "#ebe1d0",
        tertiaryFixedDim: "#cec6b5",
        onTertiaryFixed: "#1f1b11",
        onTertiaryFixedVariant: "#4c463a",

        error: "#ba1a1a",
        onError: "#ffffff",
        errorContainer: "#ffdad6",
        onErrorContainer: "#93000a",

        background: "#fcf9f4",
        onBackground: "#1c1c19",
        surface: "#fcf9f4",
        onSurface: "#1c1c19",
        surfaceVariant: "#e5e2dd",
        onSurfaceVariant: "#5a403e",
        surfaceDim: "#dcdad5",
        surfaceBright: "#fcf9f4",
        surfaceContainerLowest: "#ffffff",
        surfaceContainerLow: "#f6f3ee",
        surfaceContainer: "#f0ede8",
        surfaceContainerHigh: "#ebe8e3",
        surfaceContainerHighest: "#e5e2dd",
        surfaceTint: "#b52424",
        inverseSurface: "#31302d",
        inverseOnSurface: "#f3f0eb",
        outline: "#8e706d",
        outlineVariant: "#e2beba",
      },
    },
  },

  dark: {
    // TEMPLAR GOLD DARK (Convento)
    convento: {
      ...MD3DarkTheme,
      roundness: 8,
      colors: {
        ...MD3DarkTheme.colors,
        primary: "#ffb77f",
        onPrimary: "#4e2600",
        primaryContainer: "#ff8a00",
        onPrimaryContainer: "#613100",
        inversePrimary: "#914c00",
        primaryFixed: "#ffdcc4",
        primaryFixedDim: "#ffb77f",
        onPrimaryFixed: "#2f1500",
        onPrimaryFixedVariant: "#6f3900",

        secondary: "#ffb869",
        onSecondary: "#482900",
        secondaryContainer: "#dd8800",
        onSecondaryContainer: "#4c2b00",
        secondaryFixed: "#ffddbb",
        secondaryFixedDim: "#ffb869",
        onSecondaryFixed: "#2b1700",
        onSecondaryFixedVariant: "#673d00",

        tertiary: "#eec227",
        onTertiary: "#3c2f00",
        tertiaryContainer: "#cca400",
        onTertiaryContainer: "#4c3c00",
        tertiaryFixed: "#ffe088",
        tertiaryFixedDim: "#eec227",
        onTertiaryFixed: "#241a00",
        onTertiaryFixedVariant: "#574500",

        error: "#ffb4ab",
        onError: "#690005",
        errorContainer: "#93000a",
        onErrorContainer: "#ffdad6",

        background: "#201000",
        onBackground: "#ffddbb",
        surface: "#201000",
        onSurface: "#ffddbb",
        surfaceVariant: "#4d2e03",
        onSurfaceVariant: "#ddc1ae",
        surfaceDim: "#201000",
        surfaceBright: "#523206",
        surfaceContainerLowest: "#190b00",
        surfaceContainerLow: "#2b1700",
        surfaceContainer: "#311a00",
        surfaceContainerHigh: "#3f2400",
        surfaceContainerHighest: "#4d2e03",
        surfaceTint: "#ffb77f",
        inverseSurface: "#ffddbb",
        inverseOnSurface: "#482900",
        outline: "#a58c7b",
        outlineVariant: "#564334",
      },
    },

    // TEMPLAR GREEN DARK (Mata)
    mata: {
      ...MD3DarkTheme,
      roundness: 8,
      colors: {
        ...MD3DarkTheme.colors,
        primary: "#a1d494",
        onPrimary: "#0a3909",
        primaryContainer: "#2d5a27",
        onPrimaryContainer: "#9dd090",
        inversePrimary: "#3b6934",
        primaryFixed: "#bcf0ae",
        primaryFixedDim: "#a1d494",
        onPrimaryFixed: "#002201",
        onPrimaryFixedVariant: "#23501e",

        secondary: "#b1cfa4",
        onSecondary: "#1e3617",
        secondaryContainer: "#36502e",
        onSecondaryContainer: "#a3c196",
        secondaryFixed: "#cdebbe",
        secondaryFixedDim: "#b1cfa4",
        onSecondaryFixed: "#092005",
        onSecondaryFixedVariant: "#344d2c",

        tertiary: "#c1c9bd",
        onTertiary: "#2b322a",
        tertiaryContainer: "#4a5249",
        onTertiaryContainer: "#bdc5b9",
        tertiaryFixed: "#dde5d9",
        tertiaryFixedDim: "#c1c9bd",
        onTertiaryFixed: "#161d16",
        onTertiaryFixedVariant: "#414940",

        error: "#ffb4ab",
        onError: "#690005",
        errorContainer: "#93000a",
        onErrorContainer: "#ffdad6",

        background: "#111413",
        onBackground: "#e1e3e1",
        surface: "#111413",
        onSurface: "#e1e3e1",
        surfaceVariant: "#333534",
        onSurfaceVariant: "#c2c9bb",
        surfaceDim: "#111413",
        surfaceBright: "#373a39",
        surfaceContainerLowest: "#0c0f0e",
        surfaceContainerLow: "#191c1b",
        surfaceContainer: "#1d201f",
        surfaceContainerHigh: "#282a2a",
        surfaceContainerHighest: "#333534",
        surfaceTint: "#a1d494",
        inverseSurface: "#e1e3e1",
        inverseOnSurface: "#2e3130",
        outline: "#8c9387",
        outlineVariant: "#42493e",
      },
    },

    // TEMPLAR RED DARK (Tabuleiros)
    tabuleiros: {
      ...MD3DarkTheme,
      roundness: 8,
      colors: {
        ...MD3DarkTheme.colors,
        primary: "#ffb4ac",
        onPrimary: "#690007",
        primaryContainer: "#b22222",
        onPrimaryContainer: "#ffc8c2",
        inversePrimary: "#b52424",
        primaryFixed: "#ffdad6",
        primaryFixedDim: "#ffb4ac",
        onPrimaryFixed: "#410003",
        onPrimaryFixedVariant: "#92030f",

        secondary: "#c8c6c6",
        onSecondary: "#303030",
        secondaryContainer: "#474747",
        onSecondaryContainer: "#b6b5b4",
        secondaryFixed: "#e4e2e1",
        secondaryFixedDim: "#c8c6c6",
        onSecondaryFixed: "#1b1c1c",
        onSecondaryFixedVariant: "#474747",

        tertiary: "#ffb4a8",
        onTertiary: "#690000",
        tertiaryContainer: "#b22417",
        onTertiaryContainer: "#ffc9c0",
        tertiaryFixed: "#ffdad4",
        tertiaryFixedDim: "#ffb4a8",
        onTertiaryFixed: "#410000",
        onTertiaryFixedVariant: "#920703",

        error: "#ffb4ab",
        onError: "#690005",
        errorContainer: "#93000a",
        onErrorContainer: "#ffdad6",

        background: "#151311",
        onBackground: "#e7e1de",
        surface: "#151311",
        onSurface: "#e7e1de",
        surfaceVariant: "#373432",
        onSurfaceVariant: "#e2beba",
        surfaceDim: "#151311",
        surfaceBright: "#3b3936",
        surfaceContainerLowest: "#0f0e0c",
        surfaceContainerLow: "#1d1b19",
        surfaceContainer: "#211f1d",
        surfaceContainerHigh: "#2c2a27",
        surfaceContainerHighest: "#373432",
        surfaceTint: "#ffb4ac",
        inverseSurface: "#e7e1de",
        inverseOnSurface: "#32302e",
        outline: "#aa8986",
        outlineVariant: "#5a403e",
      },
    },
  },
};
